### ISSUE TITLE
What are the further plans for this tool?

### ISSUE THREAD

**Issue by bojanpy** [cjolowicz/poetry-up#36]
Hi @cjolowicz do you plan on continuing to commit to this repository, did you find an alternative in the meantime ?

I am interested in using the tool as a cronjob to my Gitlab CI pipeline, and I think it would be a nice tool to make library version bumping simple :)

**Comment by cjolowicz** [comment]
Unfortunately I don't have much time for this project at the moment. I'd be happy to accept contributions. But there are more mature solutions out there. For example, did you take a look at [Renovate Bot](https://docs.renovatebot.com/modules/manager/poetry/) or [Dependabot for GitLab](https://blog.jdriven.com/2021/03/running-dependabot-on-gitlab/)? (And maybe one day [pyup](https://github.com/pyupio/pyup/issues/332) will support Poetry, as well.)

**Comment by bojanpy** [comment]
Got it, thanks for the reply I will check out the solutions, but so far your tool seems simple enough and is doing quite a good job.
